export const T = {
  iron: "#0E1210",
  iron2: "#161B18",
  iron3: "#1F2521",
  chalk: "#F2EFE9",
  chalkDim: "#A9A79F",
  rust: "#C4432B",
  moss: "#8FB89B",
  brass: "#E8B94A",
  line: "rgba(242,239,233,0.09)",
};

export const CAT_COLOR = {
  Strength: T.rust,
  Hypertrophy: T.moss,
  Powerbuilding: T.brass,
  Bodybuilding: "#B9764F",
  Running: "#5B8A9A",
  Hybrid: "#C97C3D",
  "Combat Sports": "#8B3A3A",
};

/* ---------------------------------------------------------------------- */
/* PROGRAM LIBRARY — science-backed, tried-and-true templates              */
/* ---------------------------------------------------------------------- */
export const PROGRAMS = [
  {
    id: "starting-strength",
    name: "Starting Strength",
    author: "Mark Rippetoe",
    level: "Beginner",
    category: "Strength",
    daysPerWeek: 3,
    blurb: "The classic novice linear progression. Alternate Workout A and B, 3 sessions a week, adding weight almost every session on the big barbell lifts.",
    days: [
      { name: "Workout A", exercises: [
        { name: "Barbell Squat", sets: 3, reps: "5" },
        { name: "Bench Press", sets: 3, reps: "5" },
        { name: "Deadlift", sets: 1, reps: "5" },
      ]},
      { name: "Workout B", exercises: [
        { name: "Barbell Squat", sets: 3, reps: "5" },
        { name: "Overhead Press", sets: 3, reps: "5" },
        { name: "Chin-Up", sets: 3, reps: "max" },
      ]},
    ],
  },
  {
    id: "stronglifts-5x5",
    name: "StrongLifts 5×5",
    author: "Mehdi",
    level: "Beginner",
    category: "Strength",
    daysPerWeek: 3,
    blurb: "3 full-body sessions a week, alternating two workouts. Add 5lb per session while progress is easy.",
    days: [
      { name: "Workout A", exercises: [
        { name: "Barbell Squat", sets: 5, reps: "5" },
        { name: "Bench Press", sets: 5, reps: "5" },
        { name: "Barbell Row", sets: 5, reps: "5" },
      ]},
      { name: "Workout B", exercises: [
        { name: "Barbell Squat", sets: 5, reps: "5" },
        { name: "Overhead Press", sets: 5, reps: "5" },
        { name: "Deadlift", sets: 1, reps: "5" },
      ]},
    ],
  },
  {
    id: "full-body-hypertrophy",
    name: "Full Body Hypertrophy",
    author: "General strength & conditioning",
    level: "Beginner",
    category: "Hypertrophy",
    daysPerWeek: 3,
    blurb: "3 days a week hitting every muscle group with moderate reps — a step up once pure strength gets stale.",
    days: [
      { name: "Day 1", exercises: [
        { name: "Barbell Squat", sets: 3, reps: "8-10" },
        { name: "Bench Press", sets: 3, reps: "8-10" },
        { name: "Cable Row", sets: 3, reps: "8-10" },
        { name: "Plank", sets: 3, reps: "30-45s" },
      ]},
      { name: "Day 2", exercises: [
        { name: "Deadlift", sets: 3, reps: "6-8" },
        { name: "Overhead Press", sets: 3, reps: "8-10" },
        { name: "Lat Pulldown", sets: 3, reps: "8-10" },
        { name: "Calf Raise", sets: 3, reps: "12-15" },
      ]},
      { name: "Day 3", exercises: [
        { name: "Front Squat", sets: 3, reps: "8-10" },
        { name: "Incline DB Press", sets: 3, reps: "8-10" },
        { name: "Seated Cable Row", sets: 3, reps: "8-10" },
        { name: "Hanging Knee Raise", sets: 3, reps: "10-12" },
      ]},
    ],
  },
  {
    id: "texas-method",
    name: "Texas Method",
    author: "Intermediate strength staple",
    level: "Intermediate",
    category: "Strength",
    daysPerWeek: 3,
    blurb: "Weekly undulating periodization for lifters who've outgrown session-to-session progression: volume, recovery, intensity.",
    days: [
      { name: "Volume Day", exercises: [
        { name: "Barbell Squat", sets: 5, reps: "5" },
        { name: "Bench Press / OHP (alt. weekly)", sets: 5, reps: "5" },
        { name: "Deadlift or Power Clean", sets: 1, reps: "5" },
      ]},
      { name: "Recovery Day", exercises: [
        { name: "Barbell Squat (light)", sets: 2, reps: "5" },
        { name: "OHP / Bench (opposite of vol. day)", sets: 3, reps: "5" },
        { name: "Chin-Up", sets: 3, reps: "8" },
      ]},
      { name: "Intensity Day", exercises: [
        { name: "Barbell Squat (PR attempt)", sets: 1, reps: "5" },
        { name: "Bench Press / OHP (PR attempt)", sets: 1, reps: "5" },
        { name: "Deadlift (PR, alt. weeks)", sets: 1, reps: "5" },
      ]},
    ],
  },
  {
    id: "wendler-531",
    name: "5/3/1",
    author: "Jim Wendler",
    level: "Intermediate",
    category: "Strength",
    daysPerWeek: 4,
    blurb: "Percentage-based main lifts against a training max, topped with high-volume assistance work. Slow, sustainable progress.",
    days: [
      { name: "Overhead Press Day", exercises: [
        { name: "Overhead Press (5/3/1 + AMRAP)", sets: 3, reps: "5/3/1+" },
        { name: "Dip", sets: 5, reps: "10-15" },
        { name: "Chin-Up", sets: 5, reps: "10-15" },
      ]},
      { name: "Deadlift Day", exercises: [
        { name: "Deadlift (5/3/1 + AMRAP)", sets: 3, reps: "5/3/1+" },
        { name: "Hanging Leg Raise", sets: 5, reps: "10-15" },
        { name: "Back Extension", sets: 5, reps: "10-15" },
      ]},
      { name: "Bench Press Day", exercises: [
        { name: "Bench Press (5/3/1 + AMRAP)", sets: 3, reps: "5/3/1+" },
        { name: "Dumbbell Row", sets: 5, reps: "10-15" },
        { name: "Push-Up", sets: 5, reps: "10-15" },
      ]},
      { name: "Squat Day", exercises: [
        { name: "Barbell Squat (5/3/1 + AMRAP)", sets: 3, reps: "5/3/1+" },
        { name: "Leg Curl", sets: 5, reps: "10-15" },
        { name: "Ab Wheel Rollout", sets: 5, reps: "10-15" },
      ]},
    ],
  },
  {
    id: "phul",
    name: "PHUL",
    author: "Power Hypertrophy Upper Lower",
    level: "Intermediate",
    category: "Powerbuilding",
    daysPerWeek: 4,
    blurb: "Two heavy power days and two higher-rep hypertrophy days per muscle group each week — strength and size in one plan.",
    days: [
      { name: "Upper Power", exercises: [
        { name: "Bench Press", sets: 3, reps: "3-5" },
        { name: "Bent-Over Row", sets: 3, reps: "3-5" },
        { name: "Overhead Press", sets: 3, reps: "5-8" },
        { name: "Lat Pulldown", sets: 3, reps: "6-10" },
        { name: "Barbell Curl", sets: 2, reps: "6-10" },
        { name: "Tricep Pushdown", sets: 2, reps: "6-10" },
      ]},
      { name: "Lower Power", exercises: [
        { name: "Barbell Squat", sets: 3, reps: "3-5" },
        { name: "Deadlift", sets: 2, reps: "3-5" },
        { name: "Leg Press", sets: 3, reps: "10-12" },
        { name: "Leg Curl", sets: 3, reps: "6-10" },
        { name: "Calf Raise", sets: 4, reps: "6-10" },
      ]},
      { name: "Upper Hypertrophy", exercises: [
        { name: "Incline DB Press", sets: 3, reps: "8-12" },
        { name: "Seated Cable Row", sets: 3, reps: "8-12" },
        { name: "DB Shoulder Press", sets: 3, reps: "8-12" },
        { name: "Pull-Up", sets: 3, reps: "8-12" },
        { name: "DB Curl", sets: 3, reps: "8-12" },
        { name: "Skull Crusher", sets: 3, reps: "8-12" },
      ]},
      { name: "Lower Hypertrophy", exercises: [
        { name: "Front Squat", sets: 3, reps: "8-12" },
        { name: "Romanian Deadlift", sets: 3, reps: "8-12" },
        { name: "Leg Extension", sets: 3, reps: "8-12" },
        { name: "Leg Curl", sets: 3, reps: "8-12" },
        { name: "Seated Calf Raise", sets: 4, reps: "8-12" },
      ]},
    ],
  },
  {
    id: "upper-lower-4day",
    name: "Upper / Lower 4-Day",
    author: "Intermediate powerbuilding staple",
    level: "Intermediate",
    category: "Powerbuilding",
    daysPerWeek: 4,
    blurb: "A balanced 4-day split alternating upper and lower body, mixing moderate and heavier rep ranges across the week.",
    days: [
      { name: "Upper A", exercises: [
        { name: "Bench Press", sets: 4, reps: "6-8" },
        { name: "Barbell Row", sets: 4, reps: "6-8" },
        { name: "Overhead Press", sets: 3, reps: "8-10" },
        { name: "Lat Pulldown", sets: 3, reps: "8-10" },
        { name: "Barbell Curl", sets: 3, reps: "10-12" },
        { name: "Tricep Pushdown", sets: 3, reps: "10-12" },
      ]},
      { name: "Lower A", exercises: [
        { name: "Barbell Squat", sets: 4, reps: "6-8" },
        { name: "Romanian Deadlift", sets: 3, reps: "8-10" },
        { name: "Leg Press", sets: 3, reps: "10-12" },
        { name: "Leg Curl", sets: 3, reps: "10-12" },
        { name: "Calf Raise", sets: 4, reps: "12-15" },
      ]},
      { name: "Upper B", exercises: [
        { name: "Incline Bench Press", sets: 4, reps: "8-10" },
        { name: "Pull-Up", sets: 4, reps: "8-10" },
        { name: "DB Shoulder Press", sets: 3, reps: "10-12" },
        { name: "Cable Row", sets: 3, reps: "10-12" },
        { name: "Hammer Curl", sets: 3, reps: "12" },
        { name: "Overhead Tricep Extension", sets: 3, reps: "12" },
      ]},
      { name: "Lower B", exercises: [
        { name: "Deadlift", sets: 3, reps: "5" },
        { name: "Front Squat", sets: 3, reps: "8-10" },
        { name: "Walking Lunge", sets: 3, reps: "10" },
        { name: "Leg Curl", sets: 3, reps: "12" },
        { name: "Calf Raise", sets: 4, reps: "15" },
      ]},
    ],
  },
  {
    id: "ppl-hypertrophy",
    name: "Push / Pull / Legs",
    author: "Bodybuilding staple",
    level: "Intermediate",
    category: "Hypertrophy",
    daysPerWeek: 6,
    blurb: "Push, Pull, and Legs repeated twice across 6 days a week, so each muscle group gets trained twice. High volume bodybuilding split for building size.",
    days: [
      { name: "Push", exercises: [
        { name: "Bench Press", sets: 4, reps: "6-10" },
        { name: "Overhead Press", sets: 3, reps: "8-12" },
        { name: "Incline DB Press", sets: 3, reps: "8-12" },
        { name: "Lateral Raise", sets: 3, reps: "12-15" },
        { name: "Tricep Pushdown", sets: 3, reps: "10-15" },
      ]},
      { name: "Pull", exercises: [
        { name: "Deadlift", sets: 3, reps: "5-8" },
        { name: "Pull-Up", sets: 3, reps: "8-12" },
        { name: "Barbell Row", sets: 3, reps: "8-12" },
        { name: "Face Pull", sets: 3, reps: "12-15" },
        { name: "Barbell Curl", sets: 3, reps: "10-15" },
      ]},
      { name: "Legs", exercises: [
        { name: "Barbell Squat", sets: 4, reps: "6-10" },
        { name: "Romanian Deadlift", sets: 3, reps: "8-12" },
        { name: "Leg Press", sets: 3, reps: "10-15" },
        { name: "Leg Curl", sets: 3, reps: "10-15" },
        { name: "Calf Raise", sets: 4, reps: "10-15" },
      ]},
    ],
  },
  {
    id: "arnold-split",
    name: "Arnold Split",
    author: "Golden-era bodybuilding classic",
    level: "Advanced",
    category: "Bodybuilding",
    daysPerWeek: 6,
    blurb: "Chest & Back, Shoulders & Arms, and Legs repeated twice across 6 days a week. High volume, high frequency.",
    days: [
      { name: "Chest & Back", exercises: [
        { name: "Bench Press", sets: 4, reps: "8-10" },
        { name: "Incline DB Press", sets: 4, reps: "8-10" },
        { name: "Weighted Dip", sets: 3, reps: "10" },
        { name: "Barbell Row", sets: 4, reps: "8-10" },
        { name: "Pull-Up", sets: 3, reps: "10" },
        { name: "Deadlift", sets: 3, reps: "8" },
      ]},
      { name: "Shoulders & Arms", exercises: [
        { name: "Overhead Press", sets: 4, reps: "8-10" },
        { name: "Lateral Raise", sets: 4, reps: "10-12" },
        { name: "Rear Delt Fly", sets: 3, reps: "12" },
        { name: "Barbell Curl", sets: 4, reps: "8-10" },
        { name: "Tricep Dip", sets: 4, reps: "8-10" },
        { name: "Skull Crusher", sets: 3, reps: "10" },
      ]},
      { name: "Legs", exercises: [
        { name: "Barbell Squat", sets: 4, reps: "8-10" },
        { name: "Leg Press", sets: 4, reps: "10-12" },
        { name: "Walking Lunge", sets: 3, reps: "10" },
        { name: "Leg Curl", sets: 4, reps: "10-12" },
        { name: "Calf Raise", sets: 5, reps: "12-15" },
      ]},
    ],
  },
  {
    id: "base-building-runner",
    name: "Base Building Runner",
    author: "Inspired by Jack Daniels' Running Formula & 80/20 principles",
    level: "Beginner",
    category: "Running",
    daysPerWeek: 3,
    blurb: "Three weekly runs built on the 80/20 rule — most of your mileage easy, one focused quality session. The aerobic foundation almost every runner needs before adding real speed work.",
    days: [
      { name: "Easy Run Day", exercises: [
        { name: "Easy Run", sets: 1, reps: "30 min @ conversational pace" },
        { name: "Standing Calf Raise", sets: 3, reps: "15-20" },
        { name: "Plank", sets: 2, reps: "45s" },
      ]},
      { name: "Quality Session", exercises: [
        { name: "Tempo Run", sets: 1, reps: "20 min @ comfortably hard" },
        { name: "Glute Bridge", sets: 3, reps: "12-15" },
        { name: "Dead Bug", sets: 2, reps: "10 each side" },
      ]},
      { name: "Long Run Day", exercises: [
        { name: "Long Run", sets: 1, reps: "45-60 min @ easy pace" },
        { name: "Walking Lunge", sets: 2, reps: "10 each side" },
        { name: "Hanging Knee Raise", sets: 2, reps: "12" },
      ]},
    ],
  },
  {
    id: "5k-speed-builder",
    name: "5K Speed Builder",
    author: "VDOT-based pacing, inspired by Jack Daniels' Running Formula",
    level: "Intermediate",
    category: "Running",
    daysPerWeek: 4,
    blurb: "Four runs a week built around real physiological training zones — easy, threshold, and interval pace — the same structure coaches use to build speed without burning runners out.",
    days: [
      { name: "Easy Run", exercises: [
        { name: "Easy Run", sets: 1, reps: "25-30 min easy" },
      ]},
      { name: "Interval Session", exercises: [
        { name: "Interval Run", sets: 6, reps: "400m @ 5K pace, 90s rest" },
      ]},
      { name: "Tempo Run", exercises: [
        { name: "Tempo Run", sets: 1, reps: "20-25 min @ threshold pace" },
      ]},
      { name: "Long Run", exercises: [
        { name: "Long Run", sets: 1, reps: "60 min easy" },
      ]},
    ],
  },
  {
    id: "hybrid-strength-endurance",
    name: "Hybrid Athlete: Strength + Endurance",
    author: "Concurrent training principles — managing the interference effect",
    level: "Intermediate",
    category: "Hybrid",
    daysPerWeek: 5,
    blurb: "Strength and endurance without one sabotaging the other — hard lifting and hard running stay on separate days, following the research on training-interference management.",
    days: [
      { name: "Lower Strength", exercises: [
        { name: "Barbell Squat", sets: 4, reps: "6-8" },
        { name: "Romanian Deadlift", sets: 3, reps: "8-10" },
        { name: "Standing Calf Raise", sets: 3, reps: "12-15" },
      ]},
      { name: "Easy Run + Core", exercises: [
        { name: "Easy Run", sets: 1, reps: "30 min easy" },
        { name: "Plank", sets: 3, reps: "45s" },
      ]},
      { name: "Upper Strength", exercises: [
        { name: "Bench Press", sets: 4, reps: "6-8" },
        { name: "Barbell Row", sets: 4, reps: "6-8" },
        { name: "Overhead Press", sets: 3, reps: "8-10" },
      ]},
      { name: "Interval Run", exercises: [
        { name: "Interval Run", sets: 5, reps: "800m @ 5K pace, 2 min rest" },
      ]},
      { name: "Long Run", exercises: [
        { name: "Long Run", sets: 1, reps: "45-60 min easy" },
      ]},
    ],
  },
  {
    id: "bjj-strength-conditioning",
    name: "BJJ Strength & Conditioning",
    author: "Grounded in combat-sports S&C principles",
    level: "Intermediate",
    category: "Combat Sports",
    daysPerWeek: 4,
    blurb: "Built for grapplers: explosive hip power for sweeps and guard retention, rotational core strength, grip and neck endurance, and conditioning intervals matched to real round length.",
    days: [
      { name: "Strength — Squat & Pull", exercises: [
        { name: "Barbell Squat", sets: 4, reps: "5-6" },
        { name: "Barbell Row", sets: 3, reps: "8-10" },
        { name: "Neck Bridge", sets: 3, reps: "10" },
        { name: "Farmer's Carry", sets: 3, reps: "40m" },
      ]},
      { name: "Power & Conditioning", exercises: [
        { name: "Kettlebell Swing", sets: 4, reps: "15" },
        { name: "Box Jump", sets: 4, reps: "5" },
        { name: "Rowing Machine", sets: 5, reps: "2 min hard, 1 min rest" },
      ]},
      { name: "Strength — Press & Core", exercises: [
        { name: "Overhead Press", sets: 4, reps: "6-8" },
        { name: "Pull-Up", sets: 3, reps: "8-10" },
        { name: "Pallof Press", sets: 3, reps: "12 each side" },
        { name: "Wrist Roller", sets: 2, reps: "1 min" },
      ]},
      { name: "Conditioning & Grip", exercises: [
        { name: "Battle Ropes", sets: 5, reps: "30s on / 30s off" },
        { name: "Turkish Get-Up", sets: 3, reps: "5 each side" },
        { name: "Dead Hang", sets: 3, reps: "30-45s" },
      ]},
    ],
  },
  {
    id: "hybrid-race-training",
    name: "Hybrid Race Training",
    author: "Functional fitness + running hybrid, inspired by Hyrox-style race prep",
    level: "Intermediate",
    category: "Hybrid",
    daysPerWeek: 4,
    blurb: "Alternating running with loaded functional work — sled pushes, farmer carries, wall balls — training the exact skill these hybrid races test: switching between engine and strength under fatigue.",
    days: [
      { name: "Compromised Running", exercises: [
        { name: "Interval Run", sets: 4, reps: "800m" },
        { name: "Sled Push", sets: 4, reps: "20m" },
      ]},
      { name: "Strength Base", exercises: [
        { name: "Barbell Squat", sets: 4, reps: "8-10" },
        { name: "Deadlift", sets: 3, reps: "5" },
        { name: "Farmer's Carry", sets: 3, reps: "40m" },
      ]},
      { name: "Engine Day", exercises: [
        { name: "Rowing Machine", sets: 1, reps: "20 min steady" },
        { name: "Wall Ball", sets: 5, reps: "15" },
        { name: "Burpee", sets: 5, reps: "10" },
      ]},
      { name: "Race Simulation", exercises: [
        { name: "Easy Run", sets: 1, reps: "20 min" },
        { name: "Sled Pull", sets: 3, reps: "20m" },
        { name: "Kettlebell Swing", sets: 4, reps: "15" },
        { name: "Box Jump", sets: 3, reps: "8" },
      ]},
    ],
  },
];

/* ---------------------------------------------------------------------- */
/* EXERCISE LIBRARY — searchable database for building custom programs     */
/* ---------------------------------------------------------------------- */
export const EXERCISE_LIBRARY = [
  // Chest
  { name: "Barbell Bench Press", category: "Chest" },
  { name: "Incline Barbell Bench Press", category: "Chest" },
  { name: "Decline Barbell Bench Press", category: "Chest" },
  { name: "Dumbbell Bench Press", category: "Chest" },
  { name: "Incline Dumbbell Press", category: "Chest" },
  { name: "Decline Dumbbell Press", category: "Chest" },
  { name: "Dumbbell Fly", category: "Chest" },
  { name: "Incline Dumbbell Fly", category: "Chest" },
  { name: "Cable Fly", category: "Chest" },
  { name: "Low Cable Fly", category: "Chest" },
  { name: "High Cable Fly", category: "Chest" },
  { name: "Cable Crossover", category: "Chest" },
  { name: "Pec Deck Machine", category: "Chest" },
  { name: "Chest Press Machine", category: "Chest" },
  { name: "Push-Up", category: "Chest" },
  { name: "Incline Push-Up", category: "Chest" },
  { name: "Decline Push-Up", category: "Chest" },
  { name: "Push-Up Plus", category: "Chest" },
  { name: "Weighted Dip", category: "Chest" },
  { name: "Svend Press", category: "Chest" },
  { name: "Guillotine Press", category: "Chest" },
  { name: "Floor Press", category: "Chest" },
  // Back
  { name: "Deadlift", category: "Back" },
  { name: "Sumo Deadlift", category: "Back" },
  { name: "Romanian Deadlift", category: "Back" },
  { name: "Barbell Row", category: "Back" },
  { name: "Pendlay Row", category: "Back" },
  { name: "T-Bar Row", category: "Back" },
  { name: "Seated Cable Row", category: "Back" },
  { name: "One-Arm Dumbbell Row", category: "Back" },
  { name: "Chest-Supported Row", category: "Back" },
  { name: "Lat Pulldown", category: "Back" },
  { name: "Wide-Grip Lat Pulldown", category: "Back" },
  { name: "Close-Grip Lat Pulldown", category: "Back" },
  { name: "Pull-Up", category: "Back" },
  { name: "Chin-Up", category: "Back" },
  { name: "Neutral-Grip Pull-Up", category: "Back" },
  { name: "Inverted Row", category: "Back" },
  { name: "Straight-Arm Pulldown", category: "Back" },
  { name: "Face Pull", category: "Back" },
  { name: "Rack Pull", category: "Back" },
  { name: "Good Morning", category: "Back" },
  { name: "Meadows Row", category: "Back" },
  { name: "Seal Row", category: "Back" },
  { name: "Renegade Row", category: "Back" },
  { name: "Landmine Row", category: "Back" },
  // Shoulders
  { name: "Overhead Press", category: "Shoulders" },
  { name: "Seated Dumbbell Shoulder Press", category: "Shoulders" },
  { name: "Arnold Press", category: "Shoulders" },
  { name: "Push Press", category: "Shoulders" },
  { name: "Lateral Raise", category: "Shoulders" },
  { name: "Cable Lateral Raise", category: "Shoulders" },
  { name: "Front Raise", category: "Shoulders" },
  { name: "Rear Delt Fly", category: "Shoulders" },
  { name: "Reverse Pec Deck", category: "Shoulders" },
  { name: "Upright Row", category: "Shoulders" },
  { name: "Cuban Press", category: "Shoulders" },
  { name: "Shrugs", category: "Shoulders" },
  { name: "Dumbbell Shrug", category: "Shoulders" },
  { name: "Landmine Press", category: "Shoulders" },
  { name: "Bradford Press", category: "Shoulders" },
  { name: "Machine Shoulder Press", category: "Shoulders" },
  { name: "Handstand Push-Up", category: "Shoulders" },
  { name: "Pike Push-Up", category: "Shoulders" },
  { name: "Egyptian Lateral Raise", category: "Shoulders" },
  { name: "Plate Raise", category: "Shoulders" },
  { name: "Cable Y-Raise", category: "Shoulders" },
  // Biceps
  { name: "Barbell Curl", category: "Biceps" },
  { name: "EZ-Bar Curl", category: "Biceps" },
  { name: "Dumbbell Curl", category: "Biceps" },
  { name: "Hammer Curl", category: "Biceps" },
  { name: "Incline Dumbbell Curl", category: "Biceps" },
  { name: "Preacher Curl", category: "Biceps" },
  { name: "Cable Curl", category: "Biceps" },
  { name: "Concentration Curl", category: "Biceps" },
  { name: "Spider Curl", category: "Biceps" },
  { name: "Zottman Curl", category: "Biceps" },
  { name: "Drag Curl", category: "Biceps" },
  { name: "21s", category: "Biceps" },
  { name: "Waiter Curl", category: "Biceps" },
  { name: "Cross-Body Hammer Curl", category: "Biceps" },
  // Triceps
  { name: "Tricep Pushdown", category: "Triceps" },
  { name: "Rope Pushdown", category: "Triceps" },
  { name: "Overhead Tricep Extension", category: "Triceps" },
  { name: "Skull Crusher", category: "Triceps" },
  { name: "Close-Grip Bench Press", category: "Triceps" },
  { name: "Dumbbell Kickback", category: "Triceps" },
  { name: "Tricep Dip", category: "Triceps" },
  { name: "Bench Dip", category: "Triceps" },
  { name: "Diamond Push-Up", category: "Triceps" },
  { name: "Cable Overhead Extension", category: "Triceps" },
  { name: "JM Press", category: "Triceps" },
  { name: "Single-Arm Pushdown", category: "Triceps" },
  { name: "Tate Press", category: "Triceps" },
  { name: "Rolling Tricep Extension", category: "Triceps" },
  { name: "Tricep Kickback Cable", category: "Triceps" },
  // Quads
  { name: "Back Squat", category: "Quads" },
  { name: "Front Squat", category: "Quads" },
  { name: "Goblet Squat", category: "Quads" },
  { name: "Hack Squat", category: "Quads" },
  { name: "Leg Press", category: "Quads" },
  { name: "Bulgarian Split Squat", category: "Quads" },
  { name: "Walking Lunge", category: "Quads" },
  { name: "Reverse Lunge", category: "Quads" },
  { name: "Step-Up", category: "Quads" },
  { name: "Leg Extension", category: "Quads" },
  { name: "Sissy Squat", category: "Quads" },
  { name: "Zercher Squat", category: "Quads" },
  { name: "Box Squat", category: "Quads" },
  { name: "Belt Squat", category: "Quads" },
  { name: "Pistol Squat", category: "Quads" },
  { name: "Smith Machine Squat", category: "Quads" },
  // Hamstrings
  { name: "Stiff-Leg Deadlift", category: "Hamstrings" },
  { name: "Lying Leg Curl", category: "Hamstrings" },
  { name: "Seated Leg Curl", category: "Hamstrings" },
  { name: "Nordic Curl", category: "Hamstrings" },
  { name: "Single-Leg RDL", category: "Hamstrings" },
  { name: "Glute Ham Raise", category: "Hamstrings" },
  { name: "Cable Pull-Through", category: "Hamstrings" },
  { name: "Kettlebell Swing", category: "Hamstrings" },
  { name: "Swiss Ball Leg Curl", category: "Hamstrings" },
  { name: "Razor Curl", category: "Hamstrings" },
  // Glutes
  { name: "Hip Thrust", category: "Glutes" },
  { name: "Barbell Glute Bridge", category: "Glutes" },
  { name: "Cable Kickback", category: "Glutes" },
  { name: "Glute Bridge", category: "Glutes" },
  { name: "Curtsy Lunge", category: "Glutes" },
  { name: "Frog Pump", category: "Glutes" },
  { name: "Banded Lateral Walk", category: "Glutes" },
  { name: "Hip Abduction Machine", category: "Glutes" },
  { name: "Cable Hip Thrust", category: "Glutes" },
  // Calves
  { name: "Standing Calf Raise", category: "Calves" },
  { name: "Seated Calf Raise", category: "Calves" },
  { name: "Leg Press Calf Raise", category: "Calves" },
  { name: "Donkey Calf Raise", category: "Calves" },
  { name: "Single-Leg Calf Raise", category: "Calves" },
  { name: "Tibialis Raise", category: "Calves" },
  // Abs / Core
  { name: "Plank", category: "Core" },
  { name: "Side Plank", category: "Core" },
  { name: "Hanging Leg Raise", category: "Core" },
  { name: "Hanging Knee Raise", category: "Core" },
  { name: "Cable Crunch", category: "Core" },
  { name: "Sit-Up", category: "Core" },
  { name: "Weighted Sit-Up", category: "Core" },
  { name: "Russian Twist", category: "Core" },
  { name: "Ab Wheel Rollout", category: "Core" },
  { name: "Bicycle Crunch", category: "Core" },
  { name: "Reverse Crunch", category: "Core" },
  { name: "V-Up", category: "Core" },
  { name: "Dragon Flag", category: "Core" },
  { name: "Woodchopper", category: "Core" },
  { name: "Pallof Press", category: "Core" },
  { name: "Mountain Climber", category: "Core" },
  { name: "Toes to Bar", category: "Core" },
  { name: "Dead Bug", category: "Core" },
  { name: "Hollow Body Hold", category: "Core" },
  { name: "L-Sit", category: "Core" },
  // Forearms / Grip
  { name: "Wrist Curl", category: "Forearms" },
  { name: "Reverse Wrist Curl", category: "Forearms" },
  { name: "Farmer's Carry", category: "Forearms" },
  { name: "Plate Pinch", category: "Forearms" },
  { name: "Dead Hang", category: "Forearms" },
  { name: "Reverse Curl", category: "Forearms" },
  { name: "Wrist Roller", category: "Forearms" },
  { name: "Suitcase Carry", category: "Forearms" },
  { name: "Behind-the-Back Wrist Curl", category: "Forearms" },
  { name: "Fat Grip Hold", category: "Forearms" },
  // Full Body / Olympic
  { name: "Power Clean", category: "Full Body" },
  { name: "Hang Clean", category: "Full Body" },
  { name: "Clean and Jerk", category: "Full Body" },
  { name: "Snatch", category: "Full Body" },
  { name: "Hang Snatch", category: "Full Body" },
  { name: "Clean Pull", category: "Full Body" },
  { name: "Snatch Pull", category: "Full Body" },
  { name: "Thruster", category: "Full Body" },
  { name: "Man Maker", category: "Full Body" },
  { name: "Turkish Get-Up", category: "Full Body" },
  { name: "Kettlebell Clean", category: "Full Body" },
  { name: "Wall Ball", category: "Full Body" },
  { name: "Devil Press", category: "Full Body" },
  { name: "Bear Crawl", category: "Full Body" },
  // Cardio / Conditioning
  { name: "Rowing Machine", category: "Cardio" },
  { name: "Assault Bike", category: "Cardio" },
  { name: "Battle Ropes", category: "Cardio" },
  { name: "Sled Push", category: "Cardio" },
  { name: "Sled Pull", category: "Cardio" },
  { name: "Box Jump", category: "Cardio" },
  { name: "Burpee", category: "Cardio" },
  { name: "Jump Rope", category: "Cardio" },
  { name: "Stair Climber", category: "Cardio" },
  { name: "Sprint Intervals", category: "Cardio" },
  { name: "Ski Erg", category: "Cardio" },
  { name: "Shuttle Run", category: "Cardio" },
  // Running
  { name: "Easy Run", category: "Running" },
  { name: "Tempo Run", category: "Running" },
  { name: "Long Run", category: "Running" },
  { name: "Interval Run", category: "Running" },
  { name: "Fartlek Run", category: "Running" },
  { name: "Hill Sprints", category: "Running" },
  { name: "Recovery Run", category: "Running" },
  { name: "Progression Run", category: "Running" },
  // Combat Sports
  { name: "Neck Bridge", category: "Combat Sports" },
  { name: "Neck Curl", category: "Combat Sports" },
  { name: "Shrimp Escape Drill", category: "Combat Sports" },
  { name: "Sprawl Drill", category: "Combat Sports" },
  { name: "Grip Trainer Squeeze", category: "Combat Sports" },
  { name: "Towel Pull-Up", category: "Combat Sports" },
];
